language: python
dist: trusty
os: linux
python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master

jobs:
  fast_finish: true

  include:
    - if: commit_message !~ skip-tests
    - env:
      - DOCS=true

before_install:
  - |
    if [[ "$DOCS" != "true" ]]; then
      ./continuous_integration/before_install.sh
    fi

install:
  - |
    if [[ "$DOCS" != "true" ]]; then
      docker exec -it kerberosauthenticator-testing ./working/continuous_integration/install.sh
    else
      pip install jupyterhub pykerberos sphinx doctr
      pip install -e .
    fi

script:
  - |
    if [[ "$DOCS" != "true" ]]; then
      docker exec -it kerberosauthenticator-testing ./working/continuous_integration/script.sh
    else
      set -xe
      pushd docs
      make html
      popd

      # Maybe deploy documentation
      if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
          doctr deploy . --built-docs docs/build/html/
      fi
    fi

notifications:
  email: false
